name: Deploy website

on:
  workflow_dispatch:
  push:
    branches: 
      - 'master'
      - 'main'
    paths:
      - 'web/**'
  pull_request:
    types:
      - closed
    branches: 
      - 'master'
      - 'main'
    paths:
      - 'web/**'

jobs:
  build:
    if: |
      github.event.pull_request.merged == true || 
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch'
    name: Build and Copy
    env:
      CI: ''
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x 
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: web/package-lock.json
      
      - name: Install dependencies
        run: npm install
        working-directory: web

      - name: Build 
        run: npm run build --if-present
        working-directory: web

      - name: Copy build/
        uses: nogsantos/scp-deploy@master
        with:
          src: ./web/build
          remote: /home/lingon/.local/share/vattenskoter
          host: "188.149.175.143"
          port: 2277
          user: 'lingon'
          key: ${{ secrets.SERVER_KEY }}

  deploy:
    if: |
      github.event.pull_request.merged == true || 
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch'
    name: Restart web server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Reload web server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: "188.149.175.143"
          port: 2277 
          username: 'lingon'
          key: ${{ secrets.SERVER_KEY }}
          script: |
            sudo mv /home/lingon/.local/share/vattenskoter/build/* /var/www/vattenskoter.fredin.org/build/
            sudo systemctl reload nginx.service
