name: Deploy server

on:
  push:
    branches: 
      - 'master'
      - 'main'
    paths:
      - 'server/**'
  pull_request:
    types:
      - closed
    branches: 
      - 'master'
      - 'main'
    paths:
      - 'server/**'

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'master' || github.event_name = 'main'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Checkout main
      run: git checkout main    

    - name: Pull changes
      run: git pull    

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
      working-directory: server

    - name: Restart Server
      run: sudo systemctl restart vattenskoter-server.service
      working-directory: server/target
