name: Deploy server

on:
  pull_request:
    types:
      - closed
    branches: 
      - 'master'
      - 'main'
    paths:
      - 'server/**'

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
      working-directory: server

    - name: Start Server
      run: sudo systemctl restart vattenskoter-server.service
      working-directory: server/target
