name: Node.js CI

on:
  push:
    branches: [ main, story#1.3-continuous-integration ]
  pull_request:
    branches: [ main, story#1.3-continuous-integration ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        run: |
          cd web
          npm install
      - name: Run npm ci
        run: |
          cd web
          npm ci
      - name: Run npm build
        run: |
          cd web
          npm run build --if-present
      - name: Run npm test
        run: |
          cd web
          npm test
